### ISSUE TITLE
Look for and integrate i2c-controlled I/O pins.

### ISSUE THREAD

**Issue by jef-pearlman** [roscopetracula/hindenburgFights#22]

**Comment by 4levity** [comment]
working on support for new board version with i2c expander!

was going to compile separate firmware for old/new boards, controlled with #defines. but it seems like a better idea to look for i2c expander at runtime and automatically configure.

**Comment by jef-pearlman** [comment]
May I suggest reporting back to the client (a string probably) if no expander is found?  Eventually we shouldn't have boards without them, and it'll let us know if anything malfunctions.

**Comment by 4levity** [comment]
i2c expander detection, automatic pin assignment, and use of LEDs is implemented but not tested on new board yet (mostly tested to not break old board)

remaining: 
- get it actually working with expander
- notify controller (fault?) if i2c expander NOT found

**Comment by 4levity** [comment]
All tested and working now.
